version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/postgres
    environment:
      - POSTGRES_PASSWORD=sage
      - POSTGRES_USER=sage
      - POSTGRES_DB=sage

    airflow:
      image
volumes:
  postgres-data: